name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]
  merge_group:
    branches:
      - main

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    uses: forem/forem/.github/workflows/cla.yml@main
    secrets: inherit
