name: "test reusable CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened,closed,synchronize]
  merge_group:
    branches:
      - main

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    uses: forem/forem/.github/workflows/cla.yml@mac/ci/update-cla
